apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: spiderfoot-data
  name: spiderfoot-data
  namespace: spiderfoot
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
